import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import 'react-toastify/dist/ReactToastify.css'
import ToastProvider from '@/providers/toast.provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <header className="flex justify-evenly border-b py-3 px-3">
            <Link href={'/'} className="font-bold">
                Home
            </Link>
            <Link href={'/login'} className="font-bold">
                Login
            </Link>

          </header>
          {children}
        </ToastProvider>
      </body>
    </html>
  )
}
