
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import 'react-toastify/dist/ReactToastify.css'
import ToastProvider from '@/providers/toast.provider'
import NextAuthProvider from '@/providers/next-auth-provider';

const inter = Inter({ subsets: ['latin'] })

import IconUser from '@/icons/user';
import LoginBtn from '@/components/login-btn';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full flex flex-col bg-gray-100`}>
        <NextAuthProvider>
        <ToastProvider>
          <header className="flex justify-between border-b shadow bg-white">
            <Link href={'/'} className="font-bold py-3 px-3 hover:bg-blue-100">
                Home
            </Link>
          </header>
          <main className="h-full overflow-y-auto">
              {children}
          </main>
          <nav className="mt-auto flex md:hidden justify-evenly border-t bg-white">
            <Link href={'/'} className="inline-flex items-center justify-center py-2 px-2 grow font-semibold text-sm hover:bg-blue-100">
                Shop
            </Link>
            <Link href={'/account'} className="inline-flex items-center justify-center py-2 px-2 grow font-semibold text-sm hover:bg-blue-100">
                Account
            </Link>
          </nav>
        </ToastProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
