
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import 'react-toastify/dist/ReactToastify.css'
import ToastProvider from '@/providers/toast.provider'
import NextAuthProvider from '@/providers/next-auth-provider';
import Nav from '@/components/nav'

const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full bg-white`}>
        <NextAuthProvider>
          <ToastProvider>
            <div className="h-full flex flex-col md:flex-row-reverse">
              <div className="grow flex flex-col overflow-y-auto">
                <div className="px-3 py-1 text-sm text-center bg-gray-800 text-white">Android App Coming Soon</div>
                <header className="flex justify-between border-b shadow sticky top-0 bg-white">
                  <Link href={'/'} className="font-bold py-3 px-3 hover:bg-blue-100">
                    Home
                  </Link>
                </header>
                <main className="h-full">
                  {children}
                </main>
              </div>
              <div className="bg-gray-100">
              <Nav />
              </div>
            </div>
          </ToastProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
